### ISSUE TITLE
Build latest version OpenMPI and UCX library

### ISSUE THREAD

**Issue by koarakawaii** [calab-ntu/eureka#4]
## OpenMPI version
[OpenMPI 4.1.1](https://www.open-mpi.org/software/ompi/v4.1/)
## UCX version
Version 1.12.0 [Download Link](https://github.com/openucx/ucx)
[Tutorial](https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX)

**Remember to point the `mpirun` to the `bin` folder of the latest `OpenMPI` Library in the submit script!! Important!!**

## Runtime MCA Parameters Setting and Check
To set the MCA parameters when `mpirun` is initiated, referring to the script below,:
```bash
export OMPI_MCA_pml="ucx"                                       # include only ucx for pml
export OMPI_MCA_osc="ucx"                                       # include only ucx for osc
export OMPI_MCA_btl="^openib"                                   # exclude openib from btl

mpirun -map-by ppr:2:socket:pe=8 --report-bindings ./gamer 1>>log_new_version 2>&1
```
To check the MCA parameters when `mpirun` is initiated, adding the below the lines in runtime submit script:
```bash
export OMPI_MCA_mpi_show_mca_params="all"
export OMPI_MCA_mpi_show_mca_params_file="OMPI_MCA_PARAMETER_OUTPUT_FILE"
```
where `OMPI_MCA_PARAMETER_OUTPUT_FILE` is assigned by user.

>Ref 1: https://www.open-mpi.org/faq/?category=tuning
>Ref 2: https://www.open-mpi.org/faq/?category=openfabrics#run-ucx
>Ref 3: https://docs.oracle.com/cd/E19708-01/821-1319-10/mca-params.html

## Enable RPATH for mpicxx
Change `enable-new-dtags` to `disable-new-dtags` in the `linker_flags` of `share/openmpi/mpicxx-wrapper-data.txt`.

## Enable RPATH in the Makefile
Pass the assign dynamic shared library path to `FFTW_PATH` and `MPI_PATH` , then change
```
@$(CXX) -o $@ $^ $(OBJ_GPU_LINK) $(LIB) $(OPENMPFLAG);
```
to
```
@$(CXX) -o $@ $^ $(OBJ_GPU_LINK) -Wl,-rpath,$(FFTW_PATH)/lib:$(MPI_PATH)/lib $(LIB) $(OPENMPFLAG);
```
in `GAMER`'s `Makefile`.

### Setup
5 test runs using `UM_IC`+5 test runs using `RESTART` with latest `UCX` library (version 1.12.0) and `OpenMPI` (version 4.1.1) all passed, with 20 time step evolution (`eureka13` excluded). 

### Outcome
Experiment (2 test runs using `RESTART`) with latest `UCX` library (version 1.12.0) and `OpenMPI` (version 4.1.1) with `eureka13` included found below issues:
1. Time step too small crash
2. Runtime hanging

### Conclusion
1. No `Local QP operation on mlx5_0:1/IB` bug is observed.
2. Waiting for RAM test on `eureka13` to confirm memory problem.

### Tasks
- [x] Check whether dynamic linker links to the correct libraries.
- [x] Wait for the result of RAM test on `eureka13` and test it: RAM test failed on `2021/07/08` 
- [x] If everything works fine, mark this MPI as default.
  - Install at `/software/openmpi` on the login node (for both `gnu` and `intel`)
  - Make sure that it connects to our queuing system
  - Update `/etc/profile.d/openmpi.sh` on all nodes 
  - Recompile FFTW library

**Comment by hyschive** [comment]
@koarakawaii Good job! Just two quick comments.

1. One will also need to  *link* to the correct library when running MPI. For example, you could put the following lines in `~/.bashrc`, which will overwrite the default MPI setup.
``` bash
MPI_PATH=/software/openmpi/4.1.1-intel # for example
PATH=$MPI_PATH/bin:$PATH
LD_LIBRARY_PATH=$MPI_PATH/lib64:$LD_LIBRARY_PATH
```

2. Add a to-do list to the original post, including
- [ ] Wait for the result of `RAM` test on `eureka13`
- [ ] If everything works fine, mark this MPI as default.
  - Install at `/software/openmpi` on the login node (for both `gnu` and `intel`)
  - Make sure that it connects to our queuing system
  - Update `/etc/profile.d/openmpi.sh` on all nodes
